name: CodeQuality Valgrind
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Valgrid
      run: make -C 3_Implementation/ valgrind
